apiVersion: v1
data:
  # TODO specify config map key name: |
    # TODO past config
  # TODO specify config map key name: |
    # TODO past config
  ####example
  promxy.yaml: # TODO delete this config key |
    "global:\n  evaluation_interval: 5s\n  external_labels:\n    source:
    promxy\n\n\n\npromxy:\n  server_groups:\n    - static_configs:\n        - targets:\n
    \         - influx-0-2695780.lvs02.dev.ebayc3.com:9090\n          - influx-1-2798218.lvs02.dev.ebayc3.com:9090\n
    \         - influx-1-2303728.slc07.dev.ebayc3.com:9090\t\n      anti_affinity:
    20s\n      http_client:\n        tls_config:\n          insecure_skip_verify:
    true\n"
kind: ConfigMap
metadata:
  name: # TODO configmap name.
  namespace: # TODO config map name space to deploy.